evaluation:
  test_period_months: 3
  top_k_recommendations: 5
model:
  activation: relu
  dropout_rate: 0.2
  embedding_dim: 32
  hidden_layer_sizes:
  - 4
  - 2
  - 1
  output_activation: softmax
preprocessing:
  fill_value: 0
  min_interactions: 5
  unknown_category: Unknown
regularization:
  l2_strength: 0.001
training:
  batch_size: 32
  early_stopping_patience: 5
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.1
